apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: wanderlust
  labels:
    app: wanderlust-mongodb
spec:
  type: ClusterIP
  selector:
    app: wanderlust-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
