apiVersion: v1
kind: Secret
metadata:
  name: wanderlust-secrets
  namespace: wanderlust
  labels:
    app: wanderlust-backend
stringData:
  db-user: "root"
  db-pass: "root"
  jwt-secret: "70dd8b38486eee723ce2505f6db06f1ee503fde5eb06fc04687191a0ed665f3f98776902d2c89f6b993b1c579a87fedaf584c693a106f7cbf16e8b4e67e9d6df"
